on: ["pull_request"]
name: Unit tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        os: [uipath-ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@bfdd3570ce990073878bf10f6b2d79082de49492  # v2.2.0
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e  # v2.8.0
      - name: golangci-lint
        uses: golangci/golangci-lint-action@5c56cd6c9dc07901af25baab6f2b0d9f3b7c3018  # v2.5.2
        with:
          version: latest
          args: -c .golangci.yml -v
      - name: go test
        run: go test ./...
